BB2 = 'BigBrain2_PreRelease.2023/'
LIST_DIRS = {
 'surfaces_gii': 'BigBrainRelease.2015/3D_Surfaces/Apr7_2016/gii',
 'surfaces_obj': 'BigBrainRelease.2015/3D_Surfaces/Apr7_2016/wavefront-obj',
 'surfaces_stl_RECORD': 'BigBrainRelease.2015/3D_Surfaces/Apr7_2016/stl',
 'surfaces_mniobj_RECORD': 'BigBrainRelease.2015/3D_Surfaces/Apr7_2016/MNI-obj',
 'layer_plos_gii': 'BigBrainRelease.2015/Layer_Segmentation/3D_Surfaces/PLoSBiology2020/gii',
 'layer_plos_obj': 'BigBrainRelease.2015/Layer_Segmentation/3D_Surfaces/PLoSBiology2020/wavefront-obj',
 'layer_cc2018_RECORD': 'BigBrainRelease.2015/Layer_Segmentation/3D_Surfaces/CerebralCortex2018',
 'layer_april2019_RECORD': 'BigBrainRelease.2015/Layer_Segmentation/3D_Surfaces/April2019',
 'layer_2d_coronal_minc': 'BigBrainRelease.2015/Layer_Segmentation/2D_Sections/Coronal/Minc',
 'layer_2d_coronal_png': 'BigBrainRelease.2015/Layer_Segmentation/2D_Sections/Coronal/Png',
 'parcel_BB_Brainnetome': 'BigBrainRelease.2015/Surface_Parcellations/BigBrain_space/Brainnetome',
 'parcel_BB_DKT': 'BigBrainRelease.2015/Surface_Parcellations/BigBrain_space/DKT',
 'parcel_BB_Economo': 'BigBrainRelease.2015/Surface_Parcellations/BigBrain_space/Economo',
 'parcel_BB_Schaefer2018': 'BigBrainRelease.2015/Surface_Parcellations/BigBrain_space/Schaefer2018',
 'parcel_BB_HCPMMP': 'BigBrainRelease.2015/Surface_Parcellations/BigBrain_space/HCP-MMP-1.0',
 'parcel_BB_Surfaces': 'BigBrainRelease.2015/Surface_Parcellations/BigBrain_space/Surfaces',
 'parcel_fsLR_HCPMMP': 'BigBrainRelease.2015/Surface_Parcellations/fs_LR/HCP-MMP-1.0',
 'parcel_fsLR_Surfaces': 'BigBrainRelease.2015/Surface_Parcellations/fs_LR/Surfaces',
 'parcel_fsavg_RECORD': 'BigBrainRelease.2015/Surface_Parcellations/fsaverage',
 'parcel_doc_RECORD': 'BigBrainRelease.2015/Surface_Parcellations/Documentation',
 'warp_white_surfaces': 'BigBrainRelease.2015/BigBrainWarp_Support/white_surfaces',
 'warp_mni152_spheres': 'BigBrainRelease.2015/BigBrainWarp_Support/BigBrain_to_MNI152/spheres',
 'warp_mni152_in_input': 'BigBrainRelease.2015/BigBrainWarp_Support/BigBrain_to_MNI152/inmap_BigBrain_outmap_MNI152/input',
 'warp_mni152_in_output': 'BigBrainRelease.2015/BigBrainWarp_Support/BigBrain_to_MNI152/inmap_BigBrain_outmap_MNI152/output',
 'warp_mni152_rev_input': 'BigBrainRelease.2015/BigBrainWarp_Support/BigBrain_to_MNI152/inmap_MNI152_outmap_BigBrain/input',
 'warp_mni152_rev_output': 'BigBrainRelease.2015/BigBrainWarp_Support/BigBrain_to_MNI152/inmap_MNI152_outmap_BigBrain/output',
 'warp_fsLR_spheres': 'BigBrainRelease.2015/BigBrainWarp_Support/BigBrain_to_fsLR/spheres',
 'warp_fsavg_spheres': 'BigBrainRelease.2015/BigBrainWarp_Support/BigBrain_to_fsavg/spheres',
 'hippo_gii': 'BigBrainRelease.2015/Hippocampus_Segmentation/gii',
 'hippo_json_RECORD': 'BigBrainRelease.2015/Hippocampus_Segmentation/JSON',
 'hippo_stl_RECORD': 'BigBrainRelease.2015/Hippocampus_Segmentation/stl',
 'hippo_obj_RECORD': 'BigBrainRelease.2015/Hippocampus_Segmentation/wavefront-obj',
 '2d_coronal_png_full': 'BigBrainRelease.2015/2D_Final_Sections/Coronal/Png/Full_Resolution',
 '2d_coronal_png_thumb': 'BigBrainRelease.2015/2D_Final_Sections/Coronal/Png/Thumbnail',
 '2d_coronal_minc': 'BigBrainRelease.2015/2D_Final_Sections/Coronal/Minc',
 '2d_axial_png_full': 'BigBrainRelease.2015/2D_Final_Sections/Axial/Png/Full_Resolution',
 '2d_axial_png_thumb': 'BigBrainRelease.2015/2D_Final_Sections/Axial/Png/Thumbnail',
 '2d_axial_minc': 'BigBrainRelease.2015/2D_Final_Sections/Axial/Minc',
 '2d_sagittal_png_full': 'BigBrainRelease.2015/2D_Final_Sections/Sagittal/Png/Full_Resolution',
 '2d_sagittal_png_thumb': 'BigBrainRelease.2015/2D_Final_Sections/Sagittal/Png/Thumbnail',
 '2d_sagittal_minc': 'BigBrainRelease.2015/2D_Final_Sections/Sagittal/Minc',
 'microdraw_256_RECORD': 'BigBrainRelease.2015/MicroDraw/256_DZI',
 'microdraw_raw3500_RECORD': 'BigBrainRelease.2015/MicroDraw/Raw_3500',
 'BB2_root_RECORD': BB2,
 'BB2_vol_hist_nii': BB2 + '3D_Volumes/Histological_Space/nii',
 'BB2_vol_hist_mnc': BB2 + '3D_Volumes/Histological_Space/mnc',
 'BB2_vol_mni_nii': BB2 + '3D_Volumes/MNI-152_Space/nii',
 'BB2_vol_mni_transform': BB2 + '3D_Volumes/MNI-152_Space/transformation',
 'BB2_surfaces': BB2 + '3D_Surfaces',
 'BB2_2dmasks_RECORD': BB2 + '2D_Masks',
 'BB2_1micron_RECORD': BB2 + '1micron',
 'BB2_images_RECORD': BB2 + 'Images',
}
